export default {
  index: 'Introduction',
  'why-ai-kit': 'Why AI Kit',
  'ai-self-improvement': 'AI That Improves Itself',
  'getting-started': 'Getting Started',
  'cli-reference': 'CLI Reference',
  'what-gets-generated': 'What Gets Generated',
  'supported-stacks': 'Supported Tech Stacks',
  'slash-commands': 'Skills & Commands',
  hooks: 'Hooks',
  agents: 'Agents',
  'context-modes': 'Context Modes',
  guides: 'Guides',
  'recommended-tools': 'Recommended Tools',
  configuration: 'Configuration',
  'tips-and-tricks': 'Tips & Tricks',
  troubleshooting: 'Troubleshooting',
  faq: 'FAQ',
  'how-it-works': 'How It Works',
  changelog: 'Changelog',
  contributing: 'Contributing',
}
